# frontend-compose.yml

services:
  hurry-solv-web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`test.sauravkumar.cloud`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    environment:
      - VITE_BASE_URL=${VITE_BASE_URL}
    restart: always
    deploy:
      replicas: 1

networks:
  traefik-public:
    external: true

